apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-cluster
  namespace: {{ .Release.Namespace}}
spec:
  type: ClusterIP
  selector:
{{ include "selector.labels" . | indent 4}}
  ports:
    - protocol: TCP
      port: 3000          # expose or external or service port
      targetPort: 3000  #container port
